// packages/react-ui/src/button.tsx
import React from "react";
import cn from "@repo/tailwind-config/utils";
import { buttonVariants, VariantProps } from "@repo/tailwind-config/componentsDictionary";

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
  VariantProps<typeof buttonVariants> {
  children: React.ReactNode;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ children, className, variant, size, rounded, ...props }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          buttonVariants({ variant, size, rounded, className }),
        )}
        {...props}
      >
        {children}
      </button>
    );
  }
);

Button.displayName = "Button";

export { Button, buttonVariants };

// packages/vue-ui/src/button.vue
<script setup lang="ts">
import cn from "@repo/tailwind-config/utils";
import { buttonVariants } from "@repo/tailwind-config/componentsDictionary";

interface ButtonProps {
  variant?: NonNullable<Parameters<typeof buttonVariants>[0]>["variant"];
  size?: NonNullable<Parameters<typeof buttonVariants>[0]>["size"];
  rounded?: NonNullable<Parameters<typeof buttonVariants>[0]>["rounded"];
  as?: string;
}

withDefaults(defineProps<ButtonProps>(), {
  as: "button",
});
</script>

<template>
  <component
    :is="as"
    :class="cn(buttonVariants({ variant, size, rounded }), $attrs.class ?? '')"
  >
    <slot />
  </component>
</template>
